language: csharp
solution: ./src/Atomix.sln
script:
  - pushd src/Build && sudo bash ./Setup.sh --setup && popd
  - pushd libs && sudo bash ./Build-zlib.sh && popd
  - pushd libs && sudo bash ./Build-libpng.sh && popd
  - pushd libs && sudo bash ./Build-pixman.sh && popd
  - pushd libs && sudo bash ./Build-freetype.sh && popd
  - pushd libs && sudo bash ./Build-cairo.sh && popd
addons:
  apt:
    packages:
    - build-essential
    - wget
    - perl
    - texinfo
    - make
    - flex
    - bison
    - nasm
    - libz-dev
    - genisoimage
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev
